### ISSUE TITLE
Games that entirely hook & use Gamepads , don't recognize key presses

### ISSUE THREAD

**Issue by bollafa** [bollafa/GFXApiDll#2]
Emulators ( for example PCSX2 ) only read input messages from the game pad so  GFXApiDLL / Banana Splitter can't receive keyboard messages.

(Probably a LOW-keyboard hook should work) I'll fix this tomorrow as it is pretty late here. ( **lazy alert** )

**Comment by bollafa** [comment]
Fixed in last commit!

**Comment by CryZe** [comment]
Nice, it works with PCSX2 now. Still not with Dolphin, but I can work with this now :D

**Comment by bollafa** [comment]
Okey something a little weird happened.
First , I checked that it didnt work with Dolphin, ( I injected it and it didnt work ) then I simply commented out the CMD debugger and it started working, finally, i commented back the CMD debugger and it works!.

I'm smelling some [heisenbug](https://en.wikipedia.org/wiki/Heisenbug) here, but it works now!

So yeah, probably a Clean -> Build on the entire project will do the job.

![](https://puu.sh/unGqi/8e90c59d81.jpg)

**Comment by CryZe** [comment]
![http://puu.sh/unKqW.png](http://puu.sh/unKqW.png)

Not fully pretty yet, but this loads a LiveSplit file, displays the splits, scrolls when splitting, shows the attempts, shows previous segment, sum of best, possible time save, has pausing / unpausing, switching comparisons, skipping splits, undoing splits, saving as LiveSplit file (including properly recorded history and everything). Getting there :D

**Comment by CryZe** [comment]
And now it looks pretty decent too :)

![http://puu.sh/unLJO.png](http://puu.sh/unLJO.png)

**Comment by bollafa** [comment]
Holly molly! That's pretty fucking amazing! :DDDDDDDDDDDD

And you've done all those things with your livesplit-core ? Incredible!

P.S: You can change that **ehem** lovely green-neon color in the Config.txt inside Documents\BananaSplitter .
 I really want to start working on my own injector, with more configuration capabilities,( and perhaps an icon of "Banana Splitter") but lately I don't have much time ;(
